server:
  port: 8180
  servlet:
    context-path: /file-management
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/file_management?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 20
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
   com.home.fileManagement.controller: debug
